### ISSUE TITLE
Can we use flutter-auth-ui by Supabase in one version

### ISSUE THREAD

**Issue by NehalDamania** [namanh11611/flutter_mvvm_riverpod#1]
Hi,

Thanks for this great starting repo. Just one query though, can have one branch or can we replace authentication with Supabase's oun flutter-auth-ui package
https://supabase.com/docs/guides/auth/auth-helpers/flutter-auth-ui
https://pub.dev/packages/supabase_auth_ui

**Comment by namanh11611** [comment]
Thanks for your suggestion!
I've tried to apply `supabase_auth_ui` to the branch `feature/supabase_auth_ui`.
But it's hard to customize `SupaMagicAuth` and `SupaSocialsAuth` UI as I expected. So I haven't merged it yet.
Please check the `feature/supabase_auth_ui` branch.
